char WebSide[] = {
"HTTP/1.1 200 OK\r\n"
"Content-Length:1500\r\n"
"Connection: Close\r\n"
"Content-Type: text/html\r\n\r\n\r\n\r\n"
"<html>\r\n"
"<head>\r\n"
"<title>easyWEB - dynamic Webside</title>\r\n"
"</head>\r\n"
"\r\n"
"<body bgcolor=\"#F5FFFA\" text=\"#000000\">\r\n"
"<p><b><font color=\"#000000\" size=\"6\"><i>MSP430 Webserver</i></font></b></p>\r\n"
"\r\n"
"<p><b>This is a dynamic website hosted by the embedded Webserver</b> <b>easyWEB.</b></p>\r\n"
"<p><b>Hardware:</b></p>\r\n"
"<ul>\r\n"
"<li><b>MSP430F149, 60KB Flash, 2KB SRAM</b></li>\r\n"
"<li><b>Embedded DigiConnect Ethernet Module</b></li>\r\n"
"</ul>\r\n"
"\r\n"
"<p><b>A/D Converter Input 0:</b></p>\r\n"
"\r\n"
"<table bgcolor=\"#ff0000\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td>\r\n"
"<table width=\"AD7%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
"<tr><td bgcolor=\"#00ff00\">&nbsp;</td></tr>\r\n"
"</table>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"\r\n"
"<table border=\"0\" width=\"540\">\r\n"
"<tr>\r\n"
"<td width=\"14%\">0V</td>\r\n"
"<td width=\"14%\">0.5V</td>\r\n"
"<td width=\"14%\">1V</td>\r\n"
"<td width=\"14%\">1.5V</td>\r\n"
"<td width=\"14%\">2V</td>\r\n"
"<td width=\"14%\">2.5V</td>\r\n"
"<td width=\"14%\">3V</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"\r\n"
"<p><b>A/D Converter Input 1:</b></p>\r\n"
"\r\n"
"<table bgcolor=\"#ff0000\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td>\r\n"
"<table width=\"ADA%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
"<tr><td bgcolor=\"#00ff00\">&nbsp;</td></tr> \r\n"
"</table>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"\r\n"
"<table border=\"0\" width=\"540\">\r\n"
"<tr>\r\n"
"<td width=\"12%\">0V</td>\r\n"
"<td width=\"12%\">0.5V</td>\r\n"
"<td width=\"12%\">1V</td>\r\n"
"<td width=\"12%\">1.5V</td>\r\n"
"<td width=\"12%\">2V</td>\r\n"
"<td width=\"12%\">2.5V</td>\r\n"
"<td width=\"12%\">3V</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"</body>\r\n"
"</html>\r\n"
"\r\n"
};
